name: dginn
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohttp=3.8.5=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - amply=0.1.6=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=pyh71513ae_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bcrypt=4.0.1=py310hcb5633a_0
  - biopython=1.81=py310h1fa729e_0
  - boto3=1.28.52=pyhd8ed1ab_0
  - botocore=1.31.52=pyhd8ed1ab_0
  - bpp-core=2.4.1=h9f5acd7_6
  - bpp-phyl=2.4.1=h4ac6f70_4
  - bpp-popgen=2.4.1=h4ac6f70_4
  - bpp-seq=2.4.1=h4ac6f70_4
  - brotli-python=1.1.0=py310hc6cd4ac_0
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=h0c91306_1017
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.15.1=py310h2fee648_4
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=41.0.4=py310h75e40e8_0
  - datrie=0.8.2=py310h5764c6d_6
  - dbus=1.13.6=h5008d03_3
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.20.1=py310hff52083_2
  - dpath=2.1.6=pyha770c72_0
  - dropbox=11.36.2=pyhd8ed1ab_0
  - eido=0.2.1=pyhd8ed1ab_0
  - emboss=6.6.0=hdde3b0b_7
  - ete3=3.1.3=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.4.0=py310h2372a71_0
  - ftputil=5.0.4=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.36=pyhd8ed1ab_0
  - glib=2.78.0=hfc55251_0
  - glib-tools=2.78.0=hfc55251_0
  - google-api-core=2.11.1=pyhd8ed1ab_0
  - google-api-python-client=2.100.0=pyhd8ed1ab_0
  - google-auth=2.23.0=pyh1a96a4e_1
  - google-auth-httplib2=0.1.1=pyhd8ed1ab_0
  - google-cloud-core=2.3.3=pyhd8ed1ab_0
  - google-cloud-storage=2.11.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py310he8fe98e_4
  - google-resumable-media=2.6.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.60.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.57.0=py310h1b8f574_1
  - gst-plugins-base=1.22.5=h8e1006c_1
  - gstreamer=1.22.5=h98fc4e7_1
  - harfbuzz=8.2.0=h3d44ed6_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py310hff52083_4
  - hyphy=2.5.50=h0705fce_2
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - iqtree=2.2.6=h21ec9f0_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libblas=3.9.0=18_linux64_openblas
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=18_linux64_openblas
  - libclang=15.0.7=default_h7634d5b_3
  - libclang13=15.0.7=default_h9986a30_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.2.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_0
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=h74d50f4_7
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_0
  - libgpg-error=1.47=h71f35ed_0
  - libgrpc=1.57.0=ha4d0f93_1
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=18_linux64_openblas
  - liblapacke=3.9.0=18_linux64_openblas
  - libllvm15=15.0.7=h5cf9203_3
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.4=hfc447b1_0
  - libprotobuf=4.23.4=hf27288f_6
  - libsndfile=1.2.2=hbc2eb40_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_0
  - libsystemd0=254=h3516f8a_0
  - libtiff=4.5.1=h8b53f26_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.3.1=hbf2b3c1_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.5=h232c23b_1
  - libxslt=1.1.37=h0054252_1
  - libzlib=1.2.13=hd590300_5
  - logmuse=0.2.6=pyh8c360ce_0
  - lxml=4.9.3=py310h9b7343a_0
  - lz4-c=1.9.4=hcb278e6_0
  - macse=2.07=hdfd78af_0
  - mafft=7.520=h031d066_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mpg123=1.31.3=hcb278e6_0
  - mpi=1.0=openmpi
  - multidict=6.0.4=py310h1fa729e_0
  - mysql-common=8.0.33=hf1915f5_4
  - mysql-libs=8.0.33=hca2cd23_4
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - nspr=4.35=h27087fc_0
  - nss=3.92=h1d7d5a4_0
  - numpy=1.25.2=py310ha4c1d20_0
  - oauth2client=4.1.3=py_0
  - openjdk=8.0.382=hd590300_0
  - openmpi=4.1.5=h414af15_101
  - openssl=3.1.4=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - paml=4.10.6=h031d066_2
  - pandas=2.1.0=py310hcc13569_0
  - paramiko=3.3.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - peppy=0.35.7=pyhd8ed1ab_0
  - phyml=3.3.20220408=h37cc20f_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.0=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - prank=v.170427=h4ac6f70_7
  - prettytable=3.9.0=pyhd8ed1ab_0
  - protobuf=4.23.4=py310h620c231_2
  - psutil=5.9.5=py310h1fa729e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.7.0=py310hff52083_0
  - pulseaudio-client=16.1=hb77b528_5
  - pyasn1=0.5.0=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h5764c6d_2
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_4
  - pyqt5-sip=12.12.2=py310hc6cd4ac_4
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.2=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-irodsclient=1.1.8=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_0
  - qt-main=5.15.8=hc47bfe8_16
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.5.3=pyhd8ed1ab_0
  - rpds-py=0.10.3=py310hcb5633a_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.2=pyhd8ed1ab_0
  - scipy=1.11.2=py310ha4c1d20_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - setuptools-scm=7.1.0=pyhd8ed1ab_0
  - sip=6.7.11=py310hc6cd4ac_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.4.0=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.32.4=hdfd78af_0
  - snakemake-minimal=7.32.4=pyhdfd78af_0
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - traitlets=5.10.0=pyhd8ed1ab_0
  - treerecs=1.2=h9f5acd7_3
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ubiquerg=0.6.3=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h1fa729e_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.39=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py310h2372a71_0
  - yte=1.5.1=pyha770c72_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
prefix: /home/gueguen/.conda/envs/dginn
